### ISSUE TITLE
The webview is not working properly

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [mgks/Kotlin-SmartWebView#2]
**Describe the bug**
I set pull down refresh feature to true.But when i even just scroll upwards it refrershes the page.

**Expected behavior**
the webpage should scroll upwards without refreshing

**Screenshots**

**Device (please complete the following information):**
 - Samsung galaxy on7
 - Android Version [6.0.1]

**Additional context**

**Comment by mgks** [comment]
Kotlin variant of SWV came from direct conversion from Java, so it's an early stage for this variant. And I was in a rush to make this, apologies, so I didn't tested everything. I'll update the repo soon.

BTW, it's already fixed on [Java variant](https://github.com/mgks/Android-SmartWebView).

**Comment by GAGANsinghmsitece** [comment]
Thanks for informing.Hoping you will fix it here too.Apart from it, it's really a good repo.Keep it up
